name: portfolio_tracking_dbt
version: 1.0.0
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: portfolio_tracking_dbt

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# directory which will store compiled SQL files
target-path: target  

# directories to be removed by `dbt clean`
clean-targets:         
  - "target"
  - "dbt_packages"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models
models:
  portfolio_tracking_dbt:
    # default
    +materialized: view

    # models/staging/
    staging: 
      +materialized: view
      +schema: STAGING

    # models/refined/      
    refined:    
      +materialized: table
      +schema: REFINED

    # models/marts/      
    marts:
      portfolio:
        +materialized: table
        +schema: MART_PORTFOLIO

snapshots:
  portfolio_tracking_dbt:
    +target_schema: SNAPSHOTS